### ISSUE TITLE
error TS1036: Statements are not allowed in ambient context

### ISSUE THREAD

**Issue by Shin-Ogata** [UrielCh/opencv4nodejs#26]
Thank you for your quick response always.
I encountered that I couldn't compile with TypeScript  in version 6.1.4.

# Condition
As the manual says, I'm using the module like this.
```ts
import * as cv from '@u4/opencv4nodejs';
export { cv };
```

And I prepared `tsconfig.json` as follows.
```json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "es2020",
    "moduleResolution": "node",
    "outDir": "built",
    "rootDir": "src"
  },
  "include": [
    "src/**/*"
  ]
}
```

# Error Message
```sh
$ tsc -p ./tsconfig.json
node_modules/@u4/opencv4nodejs/typings/Mat.d.ts:95:2 - error TS1036: Statements are not allowed in ambient contexts.

95 };
    ~
```

# Cause of the problem
This issue is caused by an unwanted semicolon. in `Mat.d.ts`. LINE:95
- https://github.com/UrielCh/opencv4nodejs/blob/master/typings/Mat.d.ts#L95

On the other hand, I was able to confirm the correction for #19.  👍 
Thanks.

----
*@u4/opencv4nodejs version*: 6.1.4

*OpenCV version* (example 3.4.1): 4.5.4

*With OpenCV-contrib?* (extra modules): no

*OS*: Windows 11

**Comment by Shin-Ogata** [comment]
Sorry, I didn't realize [this PR](https://github.com/UrielCh/opencv4nodejs/pull/25) already existed.

**Comment by UrielCh** [comment]
all lint pushed
